version: '3'

volumes:
  dynamodb_data_test: {}

services:
  app: &app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    working_dir: /home/node/app
    volumes:
      - ../../:/home/node/app
    env_file:
      - app/.env
    command:
      - /bin/sh
      - -c
      - |
        sh app.config.sh
        npm install
        chown -R ${SERVICE_PERMISSIONS} /home/node/app
        npm offline
    networks:
      - larabot

  app_vscode:
    <<: *app
    command:
      - /bin/sh
      - -c
      - |
        sh app.config.sh
        sleep infinity
    networks:
      - larabot

  dynamodb:
    image: amazon/dynamodb-local:latest
    volumes:
      - dynamodb_data:/home/dynamodblocal
    command: '-Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal'
    networks:
      - dailybot

  dynamodb_admin:
    image: aaronshaf/dynamodb-admin:latest
    depends_on:
      - dynamodb
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    ports:
      - "8010:8001"
    networks:
      - dailybot

networks:
  larabot:
    external:
      name: larabot-project-network

